spring.application.name=movie-booking

spring.datasource.url=jdbc:h2:mem:moviedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Use a specific port for your Spring Boot app (default is 8080)
server.port=8080

# Initialize database with schema and data
spring.datasource.data=classpath:data.sql
spring.h2.console.enabled=true
# Enable Hibernate to automatically create the database schema based on entity classes
# Remove JPA/DB auto-config exclusion
spring.autoconfigure.exclude=

spring.jpa.show-sql=true